feat: Refactor authentication provider and add documentation
OpenVAA/voting-advice-application pull request #270
Opened 2023-11-20 14:02 UTC by joonatan-aatos

## WHY:

Authentication code required refactoring.

### What has been changed (if possible, add screenshots, gifs, etc. )

The structure of the code was changed.
Documentation comments were added.

## Check off each of the following tasks as they are completed

- [ ] I have reviewed the changes myself in this PR. Please check the [self-review document](https://github.com/OpenVAA/voting-advice-application/blob/main/docs/contributing/self-review.md)
- [ ] I have added or edited unit tests.
- [ ] I have run the unit tests successfully.
- [ ] I have tested this change on my own device.
- [ ] I have tested this change on other devices (Using Browserstack is recommended).
- [ ] I have tested my changes using the [WAVE extension](https://wave.webaim.org/extension/)
- [ ] I have added documentation where necessary.
- [ ] Is there an existing issue linked to this PR?

**Clean up your git commit history before submitting the pull request!**

2023-11-21 11:24 UTC, TrixterTheTux requested changes

2023-11-21 11:24 UTC, TrixterTheTux commented on frontend/src/lib/components/navigation/Navigation.svelte
> +  import RequireLogin from '../authentication/RequireLogin.svelte';
`$lib/components/authentication/RequireLogin.svelte`

2023-11-21 11:24 UTC, TrixterTheTux commented on frontend/src/lib/components/navigation/Navigation.svelte
> +        <h1>Some Of Your Data Is Still Missing</h1>
Not directly caused by this PR, but missing localization

2023-11-21 11:24 UTC, TrixterTheTux commented on frontend/src/lib/components/navigation/Navigation.svelte
> +          in the Election Compass until you have filled these, but you can login later to continue.
Not directly caused by this PR, but missing localization

2023-11-21 11:24 UTC, TrixterTheTux commented on frontend/src/lib/components/navigation/Navigation.svelte
> +          seconds.
Not directly caused by this PR, but missing localization

2023-11-21 13:14 UTC, TrixterTheTux approved these changes
Minor nitpick: `<!-- Move logout modal logic into its own component -->` could be prefixed with TODO: so it can be easily tracked by IDEs/code search.

2023-11-23 13:10 UTC, norppaa approved these changes

2023-12-01 10:16 UTC, merged