feat: Password reset page
OpenVAA/voting-advice-application pull request #306
Opened 2023-12-17 15:10 UTC by samuliys

## WHY:

Advances #189 

### What has been changed (if possible, add screenshots, gifs, etc. )

Implements the password reset page, which is used to set a new password.
The new password is validated against the same password rules as in registration.

To test the feature send the following request
Implements the password reset page, which is used to set a new password.
The page checks that the given reset code is valid and then shows the page used to set the new password.
The new password is validated against the same password rules as in registration.

To test the feature send the following request
`curl http://127.0.0.1:1337/api/auth/forgot-password -H "Content-Type: application/json" -d '{"email":"first.last@example.com"}'`

Then, navigate to http://localhost:1080/ and from the email copy the code and navigate to http://localhost:5173/candidate/password-reset?code=??? where ??? is the code you received. Then, after successfully changing the password, you are redirected to /candidate where you can log in using the new password (email is [first.last@example.com](mailto:first.last@example.com))`

## Check off each of the following tasks as they are completed

- [ ] I have reviewed the changes myself in this PR. Please check the [self-review document](https://github.com/OpenVAA/voting-advice-application/blob/main/docs/contributing/self-review.md)
- [ ] I have added or edited unit tests.
- [ ] I have run the unit tests successfully.
- [ ] I have tested this change on my own device.
- [ ] I have tested this change on other devices (Using Browserstack is recommended).
- [ ] I have tested my changes using the [WAVE extension](https://wave.webaim.org/extension/)
- [ ] I have added documentation where necessary.
- [ ] Is there an existing issue linked to this PR?

**Clean up your git commit history before submitting the pull request!**

2023-12-17 21:30 UTC, anolpe requested changes
I didn't review Stepan's commit because that will be in another PR(?)

2023-12-17 21:30 UTC, anolpe commented on frontend/src/routes/candidate/password-reset/PasswordResetPage.svelte
> +    </button>
This is not using the new button component.

2023-12-17 21:30 UTC, anolpe commented on frontend/src/routes/candidate/password-reset/PasswordResetPage.svelte
> +
Should this be named differently? Now it is `false` when the button should be disabled.

2023-12-18 15:14 UTC, suviz requested changes
Fix Antti's suggestions. Otherwise looks good!

2023-12-18 18:53 UTC, anolpe approved these changes
LGTM!

2023-12-18 19:58 UTC, suviz approved these changes
LGTM!

2023-12-19 08:39 UTC, merged