Feat/207 profile page
OpenVAA/voting-advice-application pull request #392
Opened 2024-02-28 15:31 UTC by joonatanaatos

## WHY:

Fixes [Issue link]

### What has been changed (if possible, add screenshots, gifs, etc. )

## Check off each of the following tasks as they are completed

- [x] I have reviewed the changes myself in this PR. Please check the [self-review document](https://github.com/OpenVAA/voting-advice-application/blob/main/docs/contributing/self-review.md)
- [x] I have added or edited unit tests.
- [x] I have run the unit tests successfully.
- [x] I have tested this change on my own device.
- [ ] I have tested this change on other devices (Using Browserstack is recommended).
- [x] I have tested my changes using the [WAVE extension](https://wave.webaim.org/extension/)
- [x] I have added documentation where necessary.
- [x] Is there an existing issue linked to this PR?

**Clean up your git commit history before submitting the pull request!**

2024-02-28 18:13 UTC, Henriki2305 approved these changes
Fixed some mistakes and proposed more formal sentences/terms as suggestions

2024-02-28 18:13 UTC, Henriki2305 commented on frontend/src/lib/i18n/translations/fi/candidateApp.json
> +    "commonPatterns": "Sisältää yleisiä sekvenssejä tai kuvioita"
"sekvenssejä tai kuvioita" -> "merkkisarjoja"

2024-02-28 18:13 UTC, Henriki2305 commented on frontend/src/lib/i18n/translations/fi/candidateApp.json
> +    "explanation": "Voidaksesi esiintyä vaalikompassissa sinun on annettava joitakin perustietoja itsestäsi ja vastattava poliittisia kysymyksiä koskeviin mielipidekysymyksiin.",
"vastattava poliittisia kysymyksiä koskeviin mielipidekysymyksiin" -> "ottaa kantaa poliittisiin kysymyksiin"

2024-02-29 08:36 UTC, joonatanaatos commented on frontend/src/lib/i18n/translations/fi/candidateApp.json
> +    "explanation": "Voidaksesi esiintyä vaalikompassissa sinun on annettava joitakin perustietoja itsestäsi ja vastattava poliittisia kysymyksiä koskeviin mielipidekysymyksiin.",
I'll put "vastattava poliittisiin mielipidekysymyksiin"

2024-02-29 08:36 UTC, joonatanaatos commented on frontend/src/lib/i18n/translations/fi/candidateApp.json
> +    "greeting": "Terve {username}!",
In finnish, there is no comma there

2024-02-29 08:38 UTC, joonatanaatos commented on frontend/src/lib/i18n/translations/fi/candidateApp.json
> +    "errorMessage": "Tapahtui virhe tietoja lähetettäessä!",
I think the passive form of the verb is more formal in this case, so I'll keep it the same but change the word order a bit to make it sound more natural

2024-02-29 11:08 UTC, norppaa requested changes
lgtm

2024-02-29 11:08 UTC, norppaa commented on frontend/src/hooks.server.ts
Consider fixing this

2024-03-01 07:56 UTC, norppaa approved these changes

2024-03-01 08:12 UTC, merged