Fix:relocated logout button below the warning on registration page
OpenVAA/voting-advice-application pull request #451
Opened 2024-03-30 06:21 UTC by Henriki2305

## WHY:

relocates the button for logging out when a user is logged in when trying to register below the warning

### What has been changed (if possible, add screenshots, gifs, etc. )
![image](https://github.com/OpenVAA/voting-advice-application/assets/122307901/4e494860-1c34-4a74-877d-a3d3efe15609)
![image](https://github.com/OpenVAA/voting-advice-application/assets/122307901/4a1c520e-9b00-477e-b556-7c96e69603a8)

## Check off each of the following tasks as they are completed

- [X] I have reviewed the changes myself in this PR. Please check the [self-review document](https://github.com/OpenVAA/voting-advice-application/blob/main/docs/contributing/self-review.md)
- [ ] I have added or edited unit tests.
- [X] I have run the unit tests successfully.
- [X] I have run the e2e tests successfully.
- [X] I have tested this change on my own device.
- [X] I have tested this change on other devices (Using Browserstack is recommended).
- [X] I have tested my changes using the [WAVE extension](https://wave.webaim.org/extension/)
- [X] I have added documentation where necessary.
- [X] Is there an existing issue linked to this PR?

**Clean up your git commit history before submitting the pull request!**

2024-04-03 12:26 UTC, anolpe approved these changes
LGTM!

2024-04-03 16:53 UTC, samuliys requested changes

2024-04-03 16:53 UTC, samuliys commented on frontend/src/lib/candidate/components/logoutButton/LogoutButton.svelte
> +    variant="main" />
This component is also used, for example, in the front page, which now looks like this:
![image](https://github.com/OpenVAA/voting-advice-application/assets/122277053/14f84c6f-b3fa-4a8d-9ae5-d6d5cc887743)

In the figma designs the style of the front page log out button is different so setting the variant to "main" here should probably be done in a different way. One fix would be that the variant could be given as props to the LogoutButton.

2024-04-06 16:41 UTC, samuliys requested changes

2024-04-06 16:41 UTC, samuliys commented on frontend/src/lib/candidate/components/logoutButton/LogoutButton.svelte
>    export let logoutModalTimer = 30;
As the component has become more complex I'd suggest that a `LogoutButton.type.ts` file is created with the type definitions and explanations, i.e.
```
export type LogoutButtonProps = {
  /**
   * Some text
   *
   * @default 'normal'
   */
  buttonVariant?: 'normal' | 'icon' | 'main';
  /**
   * ...
   *
   * @default false
   */
  stayOnPage?: boolean;
  /**
   * ...
   *
   * @default 30
   */
  logoutModalTimer?: number;
};
```
and then those are used instead in the component
```
import type {LogoutButtonProps} from './LogoutButton.type';

type $$Props = LogoutButtonProps;
export let buttonVariant: $$Props['buttonVariant'] = 'normal';
...
```
and so on

2024-04-06 16:41 UTC, samuliys commented on frontend/src/lib/candidate/components/logoutButton/LogoutButton.svelte
>  -->
There are also missing props in the component documentation so those should be added.
Also, the component documentation could be improved to be more in the style of the other components where the properties are clearly documented. Here is an example regarding how the properties should be documented to get a better idea:
```
### Properties

- `name`: the name of the icon to use
- `size`: The size of the icon as one of the predefined sizes 'sm', 'md' or 'lg'.
   For arbitrary values, you can supply a `class` property, such as 
   `h-[3.15rem] w-[3.15rem]`. @default 'md'
- `color`: The color of the icon as one of the predefined colours.
   For arbitrary values, you can supply a `class` property, such as
   `fill-[#123456]`. @default 'current'
- `aria-hidden`: @default `true`
- `role`: Aria role @default `img`
- `class`: Additional class string to append to the element's default classes.
```

(from `Icon.svelte`)

2024-04-06 16:41 UTC, samuliys commented on frontend/src/routes/[[lang=locale]]/candidate/(protected)/+page.svelte
> +    <LogoutButton></LogoutButton>
Should be simplified to just `<LogoutButton />`

2024-04-08 09:38 UTC, samuliys approved these changes
LGTM after the minor changes

2024-04-08 09:38 UTC, samuliys commented on frontend/src/lib/candidate/components/logoutButton/LogoutButton.svelte
> +  /*Determines whether the user is taken to the login page after logging out or stays on the current page*/
These can now be removed as they are already in the type file

2024-04-08 09:38 UTC, samuliys commented on frontend/src/lib/candidate/components/logoutButton/LogoutButton.svelte
>    /** time until automatic logout for modal */
Same with this

2024-04-08 09:38 UTC, anolpe approved these changes

2024-04-09 16:58 UTC, merged