Feat 448: No-candidate-linked-to-user-error
OpenVAA/voting-advice-application pull request #457
Opened 2024-04-03 11:17 UTC by Henriki2305

… an error

## WHY:

Fixes #448

### What has been changed (if possible, add screenshots, gifs, etc. )
![image](https://github.com/OpenVAA/voting-advice-application/assets/122307901/c509fad4-2785-4f6a-abcc-aa3cd83421aa)

## Check off each of the following tasks as they are completed

- [X] I have reviewed the changes myself in this PR. Please check the [self-review document](https://github.com/OpenVAA/voting-advice-application/blob/main/docs/contributing/self-review.md)
- [ ] I have added or edited unit tests.
- [X] I have run the unit tests successfully.
- [X] I have run the e2e tests successfully.
- [X] I have tested this change on my own device.
- [X] I have tested this change on other devices (Using Browserstack is recommended).
- [X] I have tested my changes using the [WAVE extension](https://wave.webaim.org/extension/)
- [X] I have added documentation where necessary.
- [X] Is there an existing issue linked to this PR? #448

**Clean up your git commit history before submitting the pull request!**

2024-04-03 17:17 UTC, samuliys requested changes

2024-04-03 17:17 UTC, samuliys commented on frontend/src/lib/candidate/components/candidateContext/RequireLogin.svelte
> +  import Warning from '$lib/components/warning/Warning.svelte';
Minor nitpick but this could match the style of other imports by using
`import {BasicPage} from '$lib/templates/basicPage'` and same with Warning

2024-04-03 17:17 UTC, samuliys commented on frontend/src/lib/candidate/components/candidateContext/RequireLogin.svelte
> +  userStore.subscribe((value) => (candidate = value?.candidate));
This can likely be simplified to `$: candidate = $userStore?.candidate;`

2024-04-03 17:17 UTC, samuliys commented on frontend/src/lib/candidate/components/candidateContext/RequireLogin.svelte
> +  {#if candidate != undefined}
This can be simplified to `{#if candidate}`

2024-04-03 17:17 UTC, samuliys commented on frontend/src/lib/candidate/components/candidateContext/RequireLogin.svelte
> +    <BasicPage title="">
May not be necessary but perhaps some title, even just "Error" or something, could be added?

2024-04-05 09:23 UTC, norppaa approved these changes

2024-04-05 11:12 UTC, merged